'use client';
// export const runtime = 'edge';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from './(components)/layout/Header';
import { Footer } from './(components)/layout/Footer';
import EnrollmentModal from './(components)/ui/EnrollmentModal';
import React, { useEffect, useState } from 'react';
// import { useEffect, useState } from 'react';
// import Header from './(components)/layout/Header';
// import Footer from './(components)/layout/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [isModalOpen, setIsModalOpen] = useState(false);

  useEffect(() => {
    // Check if user already submitted the form before
    const enrollmentDone = localStorage.getItem('enrollmentCompleted');
    if (!enrollmentDone) {
      setIsModalOpen(true);
    }
  }, []);

  const handleModalClose = () => {
    setIsModalOpen(false);
  };

  const handleFormSubmit = (formData) => {
    console.log('User Info:', formData);
    localStorage.setItem('enrollmentCompleted', 'true'); // Save flag
    setIsModalOpen(false);
  };
  return (
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     {children}
    //   </body>
    // </html>
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header />

        <main className="flex-1">{children}</main>

        <Footer />

        {/* Show modal only once */}
        {isModalOpen && (
          <EnrollmentModal
            isOpen={isModalOpen}
            onClose={handleModalClose}
            onSubmit={handleFormSubmit}
          />
        )}
      </body>
    </html>
  );
}
